### ISSUE TITLE
As a user, I would like more content on the homepage besides just the carousel. 

### ISSUE THREAD

**Issue by flpymonkey** [juanitotaveras/tacoboutaustin#52]
The home page looks pretty sparse, and the only hints at what your website actually does are in the navbar and the vague captions under the carousel images. It would be nice to see more information (particularly for new users) on the home page!

**Comment by tienlatien252** [comment]
We're working on it!
Estimated time: 2 hours

**Comment by juanitotaveras** [comment]
Actual time: 1 hour

Commit: 087e67d966f73c2ed04c6a8871c6c1c4938def46

We added some titles and subtitles to the carousel.
