### ISSUE TITLE
As a user, I would like the gird pages to have the expected layout on chrome.

### ISSUE THREAD

**Issue by flpymonkey** [juanitotaveras/tacoboutaustin#53]
The grid pages seem to have some layout issues on chrome where the gird items do not stack properly. This appears to be because some of the card sizes are too big (causing a gird column to be collapsed onto a new line). See the below image:
<img width="1680" alt="screen shot 2018-04-10 at 3 33 35 pm" src="https://user-images.githubusercontent.com/8204580/38582284-e08d17c0-3cd4-11e8-8cca-9825536986ab.png">

**Comment by tienlatien252** [comment]
This happen because some places have very long name. The solution is if the name is too long, we display the first part and then "..." for the rest of the string.
fix with commit 7fe9f7ec9d244c0db482a5a75f852c2d4ae2769f
