### ISSUE TITLE
As a user, I would like the filter of ratings to be a range so that I can be more precise in my filter

### ISSUE THREAD

**Issue by flpymonkey** [juanitotaveras/tacoboutaustin#54]
Right now the website only allows filtering for things above a certain rating. This is kind of pointless because everything is above a 1 star rating, which makes it hard to find only bad restaurants. I would much rather see a range for the rating filter (For example: filter by 1 star - 3 star)

**Comment by tienlatien252** [comment]
I think this is not necessary because we'll have the rating filter look like the rating filter in Amazon website, but with taco's photos instead of stars.
Estimated time: 2 hours

**Comment by tienlatien252** [comment]
The taco's images is here with commit 9b3b638920481c1954a0161c27f060d186047de4

**Comment by juanitotaveras** [comment]
We decided to not do this, since we felt the current rating options are sufficient, since we can already sort by ascending and descending rating. 
We also decided that if you can click on one star, two stars, etc., you cannot sort by half stars, which is a nice feature.

Actual time: 1 hour
