### ISSUE TITLE
As a user, I would like be able to change the direction of the sorting

### ISSUE THREAD

**Issue by flpymonkey** [juanitotaveras/tacoboutaustin#55]
Your website only allows for soring by highest rating descending and alphabetical ascending right now.

**Comment by tienlatien252** [comment]
We're planning on having a drop out for sorting which has both the order by thing(name, rating) and the order(asc, desc). Then a user can change the direction of the sorting. 
Estimated time: 5 hours

**Comment by tienlatien252** [comment]
The back end support this from commit 400b277ad464e5b8539715b800d8e10993bf90b5

**Comment by juanitotaveras** [comment]
Front-end has added ascending and descending sorting: we used a drop-down menu and react-select to make it look fancy.

Commit: a6815d18d2fab55d4e74609b0d314a317cc286cf
Actual time: 5 hours
