### ISSUE TITLE
As a user, I think the filter by zip-code should be a drop-down instead of a text box because there is a small finite value of zip-codes in Austin (and as a user I don't know most of them)

### ISSUE THREAD

**Issue by flpymonkey** [juanitotaveras/tacoboutaustin#56]
Maybe a combination dropdown and search box with autocomplete would be best so people can still type in a zip-code if they know it.

**Comment by tienlatien252** [comment]
We'll have the dropdown for all the filtering.
Estimated time: 6 hours

**Comment by juanitotaveras** [comment]
Actual time: 5 hours

Commit: 3a885c76ce2e524da32c60c202d08a38ffd458c5

We now have a drop-down for zip codes that we implemented using react-select.
