### ISSUE TITLE
As a user, I would like to know what I have sorted by after I click it

### ISSUE THREAD

**Issue by tonydenapoli** [juanitotaveras/tacoboutaustin#59]
Whenever clicking a sort button, if I click somewhere else on the page, the button deselects and I no longer know what I am sorting by. Maybe a label, or keeping the button selected would help with this.

**Comment by tienlatien252** [comment]
We're planning on having a drop out for sorting which has both the order by thing(name, rating) and the order(asc, desc). Then a user can still know what he/she has sorted by after click on one of them.
Estimated time: 5 hours

**Comment by juanitotaveras** [comment]
Added more sorting and filtering options, especially for restaurants.

Commit: 3a885c76ce2e524da32c60c202d08a38ffd458c5

Actual time: 7 hours
