### ISSUE TITLE
As a user, I would like the address to show the street address as well on the grid cards

### ISSUE THREAD

**Issue by tonydenapoli** [juanitotaveras/tacoboutaustin#60]
To me, showing just a zip code really isn't meaningful when looking at a grid. I agree you should still sort and filter by zip, but maybe display the street address on the grid page as well.

**Comment by tienlatien252** [comment]
The backend API already return the address of all places. Only need to make change the cards component to display it. This will required changing the size and layout of the card.
Estimated time: 3 hours

**Comment by juanitotaveras** [comment]
We had a heated debate about whether or not this was desired, and decided to not have the addresses on the cards, mainly because it will mess up the alignment and spacing of the cards, and we'd like to maintain consistency.

Actual time: 1 hour of heated debate
